import React from 'react';
import { SUPPORTED_MVP_MODULES } from '../services/assessmentModel';

export const DocumentationTab: React.FC = () => (
  <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
    <div className="border-b border-slate-200 bg-slate-50 p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-700">Method and limits</p><h2 className="mt-2 text-2xl font-bold text-slate-900">Evidence-led MVP boundary</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">This version is an evidence register for human assessors. It deliberately withholds posture scores, assurance ratings, and claims of automated validation.</p></div>
    <div className="space-y-8 p-6 sm:p-8">
      <section><h3 className="text-lg font-bold text-slate-900">What is supported</h3><p className="mt-2 text-sm leading-6 text-slate-600">A human assessor may record a finding only when they provide a finding title, observation, evidence reference, evidence excerpt or locator, impact statement, recommendation, and severity. The app stores this data only in the current browser session.</p><div className="mt-4 flex flex-wrap gap-2">{SUPPORTED_MVP_MODULES.map(module => <span key={module} className="rounded-full bg-cyan-50 px-3 py-1.5 text-sm font-semibold text-cyan-950 ring-1 ring-inset ring-cyan-200">{module}</span>)}</div></section>
      <section className="rounded-xl border border-amber-200 bg-amber-50 p-5"><h3 className="text-lg font-bold text-amber-950">What this MVP does not do</h3><ul className="mt-3 space-y-2 text-sm leading-6 text-amber-950"><li>• It does not parse uploads, configurations, logs, or reports to generate findings.</li><li>• It does not scan systems, validate controls, evaluate effectiveness, or calculate a risk, maturity, or posture score.</li><li>• It does not produce a compliance conclusion, certification, or assurance rating.</li><li>• Modules outside the stated boundary are shown as not supported, not as passed, failed, or assessed.</li></ul></section>
      <section><h3 className="text-lg font-bold text-slate-900">Assessment status semantics</h3><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-xl border border-slate-200 p-4"><h4 className="font-bold">Not assessed</h4><p className="mt-1 text-sm leading-6 text-slate-600">No evidence-backed human finding exists for either supported module.</p></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><h4 className="font-bold">Evidence intake incomplete</h4><p className="mt-1 text-sm leading-6 text-slate-600">Evidence exists for only part of the supported boundary. No outcome is available.</p></div><div className="rounded-xl border border-cyan-200 bg-cyan-50 p-4"><h4 className="font-bold">Evidence recorded — human review required</h4><p className="mt-1 text-sm leading-6 text-slate-600">Both supported modules have a record. This remains explicitly not an assurance conclusion.</p></div></div></section>
      <section><h3 className="text-lg font-bold text-slate-900">Responsible use</h3><p className="mt-2 text-sm leading-6 text-slate-600">Use only with authorized evidence. Review each finding against the referenced source, retain source records under your organization’s procedures, and obtain qualified review before relying on any conclusion.</p></section>
    </div>
  </div>
);
